5 спринт
dbessonovTestTasks/react-burger pull request #9
Opened 2023-03-16 16:39 UTC by dbessonovTestTasks

2023-03-16 17:22 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/Oi6pBDQ9GurghA> - По макету тут другой текст должен быть, а также должны быть активная ссылка;

- При клике по заказу открывается модальное окно с информацией о заказе и происходит переход на маршрут `/profile/orders/:id` При прямом переходе на эти маршруты открывается страница заказа. У вас не открывается роут `/profile/orders/:id` на странице заказа. <https://disk.yandex.com/i/uS7siTGl5zEtxA>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/Pxs0dagdgEgXGg>;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-03-16 17:22 UTC, ArslanDev666 commented on src/components/order-info/order-info.tsx
> +    });
**Надо исправить:**

Используйте тут `useMemo`, а не просто цикл.
Также постарайтесь указывать нормальные названия элементов, а не просто одну букву.

2023-03-16 17:22 UTC, ArslanDev666 commented on src/utils/common-types/constants.tsx
> +
**Надо исправить**

имена констант принято записывать в стиле UPPER_CASE

2023-03-17 07:37 UTC, dbessonovTestTasks commented on src/components/order-info/order-info.tsx
> +    });
Пишу тут, поскольку в коде замечание не отмечено -"В запросе /orders нужно чтобы id у булок были в начале и в конце массива: https://disk.yandex.com/i/Pxs0dagdgEgXGg;" - хотелось бы уточнить по поводу этого замечания - не понятно, что требуется сделать. Сейчас как бэк отдает список ингредиентов, так он и выводится. Где-то заказ создан логически верно, булка в начале и конце, где-то в заказе только 1 булка, где-то идут 2 подряд первыми в списке, где-то 2 подряд последними в списке, или иное. UI не может вносить со своей стороны изменения в порядок ингредиентов и состав заказа с бэка, если имеется ввиду, что требуется провести манипуляции с булками в заказе... Можете подробнее раскрыть, что по этому замечанию требуется сделать?

2023-03-17 08:37 UTC, ArslanDev666 commented on src/components/order-info/order-info.tsx
> +    });
Не совсем понял ваш вопрос, у вас есть `Post` запрос `/orders`, который выполняется, когда авторизированный пользователь жмёт на кнопку `Оформить заказ`. Вы посылаете туда массив ингредиентов и булку в конце https://disk.yandex.com/i/TDVwzQW4nP-SqA - `burger-constructor`, вам нужно добавить ещё булку в начало.

2023-03-17 09:07 UTC, dbessonovTestTasks commented on src/components/order-info/order-info.tsx
> +    });
А, при оформлении, ок. WS просто тоже на /orders идет, поэтому не понятно было, о чем речь.

2023-03-17 13:49 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-17 14:03 UTC, merged